# Generated by Django 3.1.2 on 2020-10-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogx3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blogx3.Tag'),
        ),
    ]
